* templates/configure.template: Applied some fixes from the MD config   script. * gtk-gui/MonoDevelop.Autotools.TarballBuilderEditorWidget.cs: Updated.
svn path=/trunk/monodevelop/; revision=91213

diff --git a/main/src/addins/MonoDevelop.Autotools/templates/configure.template b/main/src/addins/MonoDevelop.Autotools/templates/configure.template
--- a/main/src/addins/MonoDevelop.Autotools/templates/configure.template
+++ b/main/src/addins/MonoDevelop.Autotools/templates/configure.template
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 VERSION=%%VERSION%%
 PACKAGE=%%PACKAGE%%
 prefix=/usr/local
@@ -51,36 +51,36 @@ check_required_packages ()
 }
 
 while test x$1 != x; do
-        case $1 in
-                --prefix=*)
-                        prefix=`echo $1 | sed 's/--prefix=//'`
-                        ;;
-                --prefix)
-                        echo --prefix needs an argument: --prefix=directory >&2
-
-                        ;;
+		case $1 in
+		--prefix=*)
+				prefix=`echo $1 | sed 's/--prefix=//'`
+				;;
+		--prefix)
+				shift
+				prefix=$1
+				;;
 		--config=*)
-                        conf=`echo $1 | sed 's/--config=//'`
-			validate_config "$conf"
-			if [ $? -eq 1 ]; then
-				config=$conf
-			else
-				echo "Invalid config name - $conf"
-				usage
-				exit 1
-			fi
-                        ;;
+				conf=`echo $1 | sed 's/--config=//'`
+				validate_config "$conf"
+				if [ $? -eq 1 ]; then
+					config=$conf
+				else
+					echo "Invalid config name - $conf"
+					usage
+					exit 1
+				fi
+                ;;
 		--help)
 			usage
 			exit
 			;;
-                *)
-                        echo Unknown argument $1 >&2
+		*)
+			echo Unknown argument $1 >&2
 			usage
 			exit 1
 			;;
-        esac
-        shift
+		esac
+		shift
 done
 
 check_required_packages
