* configure: Capture prefix.
* Makefile: Add clean, install, uninstall targets.

svn path=/trunk/monodevelop/; revision=129344

diff --git a/extras/MonoDevelop.AspNet.Mvc/configure b/extras/MonoDevelop.AspNet.Mvc/configure
--- a/extras/MonoDevelop.AspNet.Mvc/configure
+++ b/extras/MonoDevelop.AspNet.Mvc/configure
@@ -1,2 +1,71 @@
 #!/bin/bash
+prefix=/usr/local
+common_packages=" mono-addins;0.3 monodevelop;1.9.2 monodevelop-core-addins;1.9.2"
 
+usage ()
+{
+	echo "Usage : configure [OPTION]... [--config=CONFIG]"
+	echo
+	echo "Options:"
+	echo "  --prefix=PREFIX         install architecture-independent files in PREFIX"
+	echo "                          [/usr/local]"
+	echo
+}
+check_package ()
+{
+	name=`echo $1 | cut -d\; -f1`
+	version=`echo $1 | cut -d\; -f2`
+
+	echo -n "Checking for package '$name'.." | tee -a config.log
+	pkg-config --atleast-version=$version $name
+	if [ $? -ne 0 ]; then
+		echo " ERROR: Package named '$name' >= $version not found." | tee -a config.log
+		echo "Try adjusting your PKG_CONFIG_PATH environment variable." | tee -a config.log
+		return 1
+	fi
+	echo " found." | tee -a config.log
+}
+
+check_required_packages ()
+{
+	echo "Looking for required packages" | tee config.log
+	var=required_packages_$config
+	for pkg in $common_packages ${!var}; do
+		check_package $pkg
+		retval=$?
+		[ $retval -ne 0 ] && return $retval
+	done
+	return 0
+}
+
+while test x$1 != x; do
+		case $1 in
+		--prefix=*)
+				prefix=`echo $1 | sed 's/--prefix=//'`
+				;;
+		--prefix)
+				shift
+				prefix=$1
+				;;
+		--help)
+			usage
+			exit
+			;;
+		*)
+			echo Unknown argument $1 >&2
+			usage
+			exit 1
+			;;
+		esac
+		shift
+done
+
+check_required_packages
+[ $? -eq 1 ] && exit 1
+
+echo "prefix=$prefix" > config.make
+
+echo
+echo "$PACKAGE has been configured with "
+echo "        prefix = $prefix"
+echo
