[build] More comprehensible error message for missing nuget
Inspired in other recent commit:
https://github.com/mono/monodevelop/commit/d4d1707fce3e158a8a982c044395e6b49cedcb40

Related bug:
https://bugzilla.xamarin.com/show_bug.cgi?id=44889

diff --git a/main/Makefile.am b/main/Makefile.am
--- a/main/Makefile.am
+++ b/main/Makefile.am
@@ -21,8 +21,16 @@ clean-local: sln_clean
 	cd external && $(MAKE) clean
 	cd build && $(MAKE) clean
 
-restore-packages:
+NUGET_FOUND = $$(echo $$(which nuget))
+NUGET_RESTORE = \
+	if [ "x$(NUGET_FOUND)" = "x" ]; then \
+		echo "nuget not found; please install it first"; \
+		exit 1; \
+	fi; \
 	nuget restore
+
+restore-packages:
+	@$(NUGET_RESTORE)
 
 vcrevision:
 	touch vcrevision
